#pragma once

// UI STRINGS
#define				UI_FILENAVIGATOR				1
#define				UI_APPPROPERTIES				2
#define				UI_TABCONTROL					3
#define				UI_SAMPLEMANAGER				4

#define				UI_IMPORT_FILE_CONTENT			10
#define				UI_IMPORT_ACTION				11

#define				UI_DATAEXCHANGE_FINALIZE		12
#define				UI_CANCEL						13
#define				UI_DATAEXCHANGE_COMREADY		14
#define				UI_EDITCONTROL_SELECTIONRANGE	15
#define				UI_EDITCONTROL_LINE				16
#define				UI_EDITCONTROL_COLUMN			17

#define				UI_TTP_SMPMNGR_ADDSAMPLE		20
#define				UI_TTP_SMPMNGR_ADDFILTER		21
#define				UI_TTP_SMPMNGR_COPYTOCLIPBOARD	22
#define				UI_TTP_SMPMNGR_CHANGESAMPLE		23
#define				UI_TTP_SMPMNGR_REMOVESAMPLE		24

#define				UI_SMP_INSERTSAMPLE				25
#define				UI_SMP_NEWFILTER_PLACEHOLDER	26
#define				UI_SMP_TEMPLATEFOLDER			27
#define				UI_SMP_SAMPLEFOLDER				28
#define				UI_SMP_REJECT					29
#define				UI_SMP_SAVESAMPLE				30
#define				UI_SMP_CHANGEELEMENT			31

#define				UI_SMP_CONFIRM_REMOVEFILTER		32
#define				UI_SMP_CONFIRM_DELETESAMPLE		33

#define				UI_SMP_CAPTIONCONFIRMATION		34
#define				UI_SMP_MAXLEVELREACHED			35
#define				UI_SMP_OVERRIDESAMPLE			36

#define				UI_GNRL_NAME					40
#define				UI_GNRL_DESCRIPTION				41
#define				UI_GNRL_CONTENT					42
#define				UI_GNRL_COPYTOCLIPBOARD			43

#define				UI_GNRL_NAMEINVALID				44

#define				UI_GNRL_ADDTAB					45
#define				UI_GNRL_OPEN					46
#define				UI_GNRL_SAVE					47
#define				UI_GNRL_SAVEAS					48
#define				UI_GNRL_SAVEALL					49
#define				UI_GNRL_CUT						50
#define				UI_GNRL_COPY					51
#define				UI_GNRL_PASTE					52
#define				UI_GNRL_DELETE_SELECTEDTEXT		53
#define				UI_GNRL_SELECTALL				54
#define				UI_GNRL_SENDPROGRAM				55
#define				UI_GNRL_RECEIVEPROGRAM			56
#define				UI_GNRL_IMPORT					57
#define				UI_GNRL_TEMPLATEMANAGER			58
#define				UI_GNRL_APPLICATIONPROPERTIES	59

#define				UI_GNRL_NEWCNCFILE				60
#define				UI_GNRL_NEWFOLDER				61
#define				UI_GNRL_COPYFOLDER				62
#define				UI_GNRL_DELETE					63
#define				UI_GNRL_RENAME					64
#define				UI_GNRL_CONVERTTOCNC3			65
#define				UI_GNRL_IMPORTCONTENT			66
#define				UI_GNRL_COPYFILE				67
#define				UI_GNRL_CHANGEROOTDIR			68
#define				UI_GNRL_PASTEFILE				69
#define				UI_GNRL_OPENFILE				70
#define				UI_GNRL_KEEPOLDFILE				71
#define				UI_GNRL_ADVANCED				72
#define				UI_GNRL_PLAIN_SAVE				73
#define				UI_GNRL_NEWPROGRAM_PLACEHOLDER	74
#define				UI_GNRL_NEWFOLDER_PLACEHOLDER	75
#define				UI_GNRL_UNDO					76
#define				UI_GNRL_REDO					77
#define				UI_GNRL_OPENINNEWTAB			78
#define				UI_GNRL_PLAIN_OPEN				79
#define				UI_GNRL_OPENHELP				80
#define				UI_GNRL_VISITWEBSITE			81
#define				UI_GNRL_CLOSEAPP				82
#define				UI_GNRL_NAVIGATEBACK			83
#define				UI_GNRL_SHOWINWINEXPLORER		84
#define				UI_GNRL_CANCEL					85
#define				UI_GNRL_FINALIZE				86
#define				UI_GNRL_INPUT					87
#define				UI_GNRL_OUTPUT					88
#define				UI_GNRL_CLOSE					89

#define				UI_NAV_SEARCHINROOT				90
#define				UI_NAV_SELECTROOTFOLDER			91
#define				UI_NAV_EXPLORERBUTTON			92
#define				UI_NAV_TEMPLATEBUTTON			93


#define				UI_EDITTOOLBAR_UPPERCASE		110
#define				UI_EDITTOOLBAR_LINENUMBERS		111
#define				UI_EDITTOOLBAR_AUTOCOMPLETE		112
#define				UI_EDITTOOLBAR_TEXTCOLOR		113
#define				UI_EDITTOOLBAR_MARKCOLOR		114
#define				UI_EDITTOOLBAR_CONVERTALL		115
#define				UI_EDITTOOLBAR_SEQUENCELINENBR	116
#define				UI_EDITTOOLBAR_CHECKFORERROR	117
#define				UI_EDITTOOLBAR_AUTOSYNTAX		118
#define				UI_EDITTOOLBAR_TEXTPROPERTIES	119
#define				UI_EDITTOOLBAR_SHOWDOCPROPERTY	120
#define				UI_EDITTOOLBAR_HIDEDOCPROPERTY	121

#define				UI_TABCTRL_DOCUMENTPROPERTIES	125
#define				UI_TABCTRL_NEWTAB				126
#define				UI_TABCTRL_DESCPLACEHOLDER_1	127
#define				UI_TABCTRL_DESCPLACEHOLDER_2	128
#define				UI_TABCTRL_DESCPLACEHOLDER_3	129
#define				UI_TABCTRL_TTBUTTONCOPYDESC		130
#define				UI_TABCTRL_TTBUTTONINSERTDESC	131
#define				UI_TABCTRL_TTBUTTONSETDIAMETER	132
#define				UI_TABCTRL_TTBUTTONDELETEDESC	133
#define				UI_TABCTRL_FONTHEIGHT			134
#define				UI_TABCTRL_LINEOFFSET			135
#define				UI_TABCTRL_FONTBOLD				136
// tabcontrol string id's continue at index 450

#define				UI_PROPWND_SETTINGSBUTTON		140
#define				UI_PROPWND_TABCTRLBUTTON		141
#define				UI_PROPWND_FILENAVIGATOR		142
#define				UI_PROPWND_EDITOR				143
#define				UI_PROPWND_EXCHANGE				144
#define				UI_PROPWND_INFO					145

#define				UI_PROPWND_LANGUAGE				146
#define				UI_PROPWND_SYSTEMLANGUAGE		147
#define				UI_PROPWND_GERMAN				148
#define				UI_PROPWND_ENGLISH				149
#define				UI_PROPWND_DESIGN				150
#define				UI_PROPWND_DSG_BLACK			151
#define				UI_PROPWND_DSG_GREY				152
#define				UI_PROPWND_DSG_LIGHT			153
#define				UI_PROPWND_DSG_GREEN			154
#define				UI_PROPWND_AUTOUPDATESEARCH		155
#define				UI_PROPWND_ACTIONONLAUNCH		156
#define				UI_PROPWND_SAVEEXPLORERCOND		157
#define				UI_PROPWND_SAVETABWNDCOND		158
#define				UI_PROPWND_SAVEUNSAVEDCONTENT	159
#define				UI_PROPWND_UPDATING				160
#define				UI_PROPWND_SEARCHFORUPDATESNOW	161
#define				UI_PROPWND_APPUPTODATE			162
#define				UI_PROPWND_UPDATEAVAILABLE		163
#define				UI_PROPWND_ERRORNOINTERNETCON	164
#define				UI_PROPWND_AUTOSAVE				165
#define				UI_PROPWND_OPENNEWFILEINNEWTAB	166
#define				UI_PROPWND_SHOWDOCPROPERTIES	167
#define				UI_PROPWND_DOCPROPTAGDESC		168
#define				UI_PROPWND_PROPDESCRIPTOR		169
#define				UI_PROPWND_ALWAYSEXPANDPATH		170
#define				UI_PROPWND_COLORSCHEME			171
#define				UI_PROPWND_NORMAL				172
#define				UI_PROPWND_SEARCHFORERRORS		173
#define				UI_PROPWND_AUTOCOMPLETESTRINGS	174
#define				UI_PROPWND_EDITACSTRINGS		175
#define				UI_PROPWND_ERRORCONTROL			176
#define				UI_PROPWND_COMPORTNUMBER		177
#define				UI_PROPWND_BAUDRATE				178
#define				UI_PROPWND_PARITY				179
#define				UI_PROPWND_DATABITS				180
#define				UI_PROPWND_STOPBITS				181
#define				UI_PROPWND_NOPARITY				182
#define				UI_PROPWND_ODDPARITY			183
#define				UI_PROPWND_EVENPARITY			184
#define				UI_PROPWND_MARKPARITY			185
#define				UI_PROPWND_SPACEPARITY			186
#define				UI_PROPWND_FLOWCTRL				187
#define				UI_PROPWND_FLOWCTRL_NONE		188
#define				UI_PROPWND_FLOWCTRL_XONXOFF		189
#define				UI_PROPWND_FLOWCTRL_HARDWARE	190
#define				UI_PROPWND_PERFORMPARITYCHECK	191
#define				UI_PROPWND_ABORTONERROR			192
#define				UI_PROPWND_REPLACEPARITYERROR	193
#define				UI_PROPWND_DTRFLOWCONTROL		194
#define				UI_PROPWND_RTSFLOWCONTROL		195
#define				UI_PROPWND_CHARACTERS			196
#define				UI_PROPWND_INTERFACECONFIG		197
#define				UI_PROPWND_MANAGECOLORSCHEMES	198
#define				UI_PROPWND_CHOOSECOLOR			199
#define				UI_PROPWND_NEWSCHEME			200
#define				UI_PROPWND_ANNOTATION			201
#define				UI_PROPWND_DEFAULTTEXTCOLOR		202
#define				UI_PROPWND_LINENUMBERCOLOR		203
#define				UI_PROPWND_BACKGROUNDCOLOR		204
#define				UI_PROPWND_RESETTEXTCOLOR		205
#define				UI_PROPWND_RESETBACKGROUND		206
#define				UI_PROPWND_ADDAUTOCOMPL			207
#define				UI_PROPWND_DELETEAUTOCOMPL		208
#define				UI_PROPWND_WHENINSERT			209
#define				UI_PROPWND_APPEND				210
#define				UI_PROPWND_PREVIEW				211
#define				UI_PROPWND_OPENCREATEDFILE		212
#define				UI_PROPWND_USEFILETAGSASTOOLTIP	213
#define				UI_PROPWND_SEARCHSETTINGS		214
#define				UI_PROPWND_SRCH_OPENMULTIFILE	215
#define				UI_PROPWND_SRCH_EXPANDPATH		216
#define				UI_PROPWND_SRCH_CLOSEONOPEN		217
#define				UI_PROPWND_SEARCHFORFILENAME	218
#define				UI_PROPWND_SEARCHFORFOLDERNAME	219
#define				UI_PROPWND_SEARCH_IN			220
#define				UI_PROPWND_AUTOSYNTAX			221
#define				UI_PROPWND_SETAUTOSYNTAX		222
#define				UI_PROPWND_CONVERTSYNTAXONOPEN	223
#define				UI_PROPWND_LINENUMBERS			224
#define				UI_PROPWND_AUTONUMSTARTLINE		225
#define				UI_PROPWND_NUMSTEPMAIN			226
#define				UI_PROPWND_NUMLENGTHMAIN		227
#define				UI_PROPWND_MINIMUMLINENUMBER		228
#define				UI_PROPWND_MAXIMUMLINENUMBER			229
#define				UI_PROPWND_ERASELINENRONBACKSPACE			230
#define				UI_PROPWND_NOSPACEINLINENUMBER				231
#define				UI_PROPWND_USEDIFFERENTLINENUMBERINSUB		232
#define				UI_PROPWND_NUMLENGTHSUB						233
#define				UI_PROPWND_NUMSTEPSUB						234
#define				UI_PROPWND_NEWEVENLINENUMBERRONTRIGGER		235
#define				UI_PROPWND_ENDPROGDETECTION					236
#define				UI_PROPWND_USEENDPROGDETECTION				237
#define				UI_PROPWND_ANNOTATIONANDVARIABLESTATEMENTS	238
#define				UI_PROPWND_AUTOCOMPLETEBRACKETS				239
#define				UI_PROPWND_INSERTSPACESINAUTOCMPLTBARCKET	240
#define				UI_PROPWND_USEMULTILINEANNOTATIONS			241
#define				UI_PROPWND_SUBPROGDETECTION					242
#define				UI_PROPWND_TRIGGER							243
#define				UI_PROPWND_PROGRAMRESTARTNECCESSARY			244

#define				UI_PROPWND_STANDARDTEMPLATE					245
#define				UI_PROPWND_INSERTSTANDARDTEMPLATE			246
#define				UI_PROPWND_CREATEDEVICELISTING				247
#define				UI_PROPWND_SELECTDEVICE						248
#define				UI_PROPWND_FOUNDDEVICES						249
#define				UI_PROPWND_NODEVICESELECTED					250
#define				UI_PROPWND_OUTPUTSETTINGS					251
#define				UI_PROPWND_OUTWINDOWSETTINGS				252
#define				UI_PROPWND_OUTFORMATSETTINGS				253
#define				UI_PROPWND_ANCHOROUTPUTWINDOW				254
#define				UI_PROPWND_MONITORTRANSMISSON				255
#define				UI_PROPWND_VERBOSETRANSMISSION				256
#define				UI_PROPWND_AUTOCLOSE						257
#define				UI_PROPWND_RESETBUTTON						258
#define				UI_PROPWND_DISCREET							259
#define				UI_PROPWND_DELETECURRENTSCHEME				260
#define				UI_PROPWND_REMOVEAPOSTROPHECOMMENT			261
#define				UI_PROPWND_REMOVEBRACKETCOMMENT				262
#define				UI_PROPWND_REMOVESPACES						263



#define				UI_EXPLORER_TOOLTIP_LOADROOTFOLDER			300
#define				UI_EXPLORER_TOOLTIP_NEWPROGRAMM				301
#define				UI_EXPLORER_TOOLTIP_NEWFOLDER				302
#define				UI_EXPLORER_TOOLTIP_COPYELEMENT				303
#define				UI_EXPLORER_TOOLTIP_INSERTELEMENT			304
#define				UI_EXPLORER_TOOLTIP_DELETEELEMENT			305
#define				UI_EXPLORER_TOOLTIP_CONVERTTOCNC3			306
#define				UI_EXPLORER_TOOLTIP_IMPORTCONTENT			307
#define				UI_EXPLORER_TOOLTIP_SEARCHFORPROGRAMM		308

#define				UI_SSCREEN_LOADING				330
#define				UI_SSCREEN_INITAPPDATA			331
#define				UI_SSCREEN_VERIFYFILESYSTEM		332
#define				UI_SSCREEN_LOADEDITRESOURCES	333
#define				UI_SSCREEN_INITMAINFRAME		334

#define				UI_STATUSBAR_READY_STATE		350
#define				UI_STATUSBAR_SENDINPROGRESS		351
#define				UI_STATUSBAR_RECEIVEINPROGRESS	352

#define				UI_PROGRESS_COLLECTINGDATA		400
#define				UI_PROGRESS_LOADINGDATA			401

#define				UI_SEARCHCTRL_MAXSRCHRESULT		402

#define				UI_TABCTRL_EXPANDPATHTOFILE		450
#define				UI_TABCTRL_ERASETABCONTENT		451
#define				UI_TABCTRL_COPYCONTENTTONEWTAB	452
#define				UI_TABCTRL_SETCONTENTASTEMPLATE	453

#define				UI_RESETWND_CHOOSECOMPONENT		500
#define				UI_RESETWND_COMPARAMETER		501
#define				UI_RESETWND_COMMONSETTINGS		502
#define				UI_RESETWND_AUTOSYNTAXSETUP		503
#define				UI_RESETWND_USERTEXT			504
#define				UI_RESETWND_INTERNALSETUP		505
#define				UI_RESETWND_AUTOCOMPLETESETUP	506
#define				UI_RESETWND_APPDATA				507
#define				UI_RESETWND_SESSIONDATA			508
#define				UI_RESETWND_RESTARTMESSAGE		515

#define				UI_PROPWND_SAVEHISTORY			550
#define				UI_PROPWND_DELETEHISTORYNOW		551


#define				UI_GNRL_COPYRIGHT				600
#define				UI_GNRL_RIGHTS					601
#define				UI_GNRL_USERCANCELCONFIRM		602
#define				UI_GNRL_NEWSUBFOLDER			603
#define				UI_GNRL_LINEENDFORMAT			604
#define				UI_GNRL_HISTORY					605

#define				UI_FILETIME_CREATED				630
#define				UI_FILETIME_LASTWRITE			631
#define				UI_FILETIME_LASTACCESS			632
#define				UI_FILEINFO						633
#define				UI_FILESIZE						634
#define				UI_OUTPUTSIZE					635

// ERROR STRINGS
#define				UI_XML_ERR_UNEXPECTEDCLOSINGTAG		800
#define				UI_XML_ERR_DOCUMENTFORMAT_INVALID	801
#define				UI_XML_ERR_NOCLOSING_ELEMENT_P1		802
#define				UI_XML_ERR_NOCLOSING_ELEMENT_P2		803

#define				ERROR_MSG_FILETYPE_NOTSUPPORTED		804
#define				ERROR_MSG_ROOTFOLDERINVALIDATED		805
#define				ERROR_MSG_ROOTFOLDERLOADINGFAILED	806
#define				ERROR_MSG_DRIVELOADINGNOTALLOWED	807
#define				ERROR_MSG_EXPORT_FAILED				808
#define				ERROR_MSG_OPENFILE_FAILED			809
#define				ERROR_MSG_IMPORT_FAILED				810
#define				ERROR_MSG_CNC3FILEOBJECT_ERROR		811
#define				ERROR_MSG_OPENFOLDER_FAILED			812

// WARNING STRINGS
#define			WARNING_MSG_UPDATESEARCH_FAILED		900
#define			WARNING_MSG_SAVEALL_NOPATHFOUND		901

// INFO STRINGS
#define			INFO_MSG_FILEWASIMPORTED		1000
#define			INFO_MSG_FILEWASCONVERTED		1001
#define			INFO_MSG_UPDATEAVAILABLE		1002
#define			INFO_MSG_LASTTABNOCLOSE			1003
#define			INFO_MSG_MAXIMUMTABCOUNTREACHED	1004
#define			INFO_MSG_FILEISALREADYOPEN		1005
#define			INFO_MSG_CHANGESNEEDRESTART		1006
#define			INFO_MSG_NOTARGETSELECTED		1007

// DIALOG STRINGS
#define			DLG_MSG_FILENOTSAVEDSAVENOW		2000
#define			DLG_MSG_UNSAVEDCONTENTEXISTS	2001




