
// IMAGE RESOURCE >>
#define			IDI_CNCSUITE_NORM			100			// LOWEST IMAGE ID FOR CONFORMITY ON ALL SYSTEMS
#define			IDI_CNCSUITE_SMLL			101

#define			IDI_APPSYSICON				102
#define			IDI_SIZECROSS				103

// free

#define			IDI_CLOSEBUTTON				105
#define			IDI_CLOSEBUTTON_MARKED		106
#define			IDI_CLOSEBUTTON_PRESSED		107
#define			IDI_SIZE_ARROW				108
#define			IDI_SIZE_ARROW_DISABLED		109
#define			IDI_TOOLBAR_NEW				110
#define			IDI_TOOLBAR_NEW_MARKED		111
#define			IDI_TOOLBAR_NEW_PRESSED		112
#define			IDI_TOOLBAR_OPEN			113
#define			IDI_TOOLBAR_OPEN_MARKED		114
#define			IDI_TOOLBAR_OPEN_PRESSED	115
#define			IDI_TOOLBAR_SAVE			116
#define			IDI_TOOLBAR_SAVE_MARKED		117
#define			IDI_TOOLBAR_SAVE_PRESSED	118
#define			IDI_TOOLBAR_SAVEALL			119
#define			IDI_TOOLBAR_SAVEALL_MARKED	120
#define			IDI_TOOLBAR_SAVEALL_PRESSED	121
#define			IDI_TOOLBAR_SAVEAS			122
#define			IDI_TOOLBAR_SAVEAS_MARKED	123
#define			IDI_TOOLBAR_SAVEAS_PRESSED	124
#define			IDI_TOOLBAR_COPY			125
#define			IDI_TOOLBAR_COPY_MARKED		126
#define			IDI_TOOLBAR_COPY_PRESSED	127
#define			IDI_TOOLBAR_PASTE			128
#define			IDI_TOOLBAR_PASTE_MARKED	129
#define			IDI_TOOLBAR_PASTE_PRESSED	130
#define			IDI_TOOLBAR_CUT				131
#define			IDI_TOOLBAR_CUT_MARKED		132
#define			IDI_TOOLBAR_CUT_PRESSED		133
#define			IDI_TOOLBAR_SELECTALL		134
#define			IDI_TOOLBAR_SELECTALL_MARKED	135
#define			IDI_TOOLBAR_SELECTALL_PRESSED	136
#define			IDI_TOOLBAR_DELETE			137
#define			IDI_TOOLBAR_DELETE_MARKED	138
#define			IDI_TOOLBAR_DELETE_PRESSED	139
#define			IDI_TOOLBAR_IMPORT			140
#define			IDI_TOOLBAR_IMPORT_MARKED	141
#define			IDI_TOOLBAR_IMPORT_PRESSED	142
#define			IDI_TOOLBAR_DROPDOWN		143
#define			IDI_TOOLBAR_DROPDOWN_MARKED		144
#define			IDI_TOOLBAR_DROPDOWN_PRESSED	145
#define			IDI_TOOLBAR_EXPORT			146
#define			IDI_TOOLBAR_EXPORT_MARKED	147
#define			IDI_TOOLBAR_EXPORT_PRESSED	148
#define			IDI_TOOLBAR_SEND			149
#define			IDI_TOOLBAR_SEND_MARKED		150
#define			IDI_TOOLBAR_SEND_PRESSED	151
#define			IDI_TOOLBAR_RECEIVE			152
#define			IDI_TOOLBAR_RECEIVE_MARKED	153
#define			IDI_TOOLBAR_RECEIVE_PRESSED	154
// application system icons
#define			IDI_APPSETTINGS				155
#define			IDI_APPSETTINGS_MARKED		156
#define			IDI_APPSETTINGS_PRESSED		157

#define			IDI_WEB						158
#define			IDI_WEB_MARKED				159
#define			IDI_WEB_PRESSED				160

#define			IDI_QUIT					161
#define			IDI_QUIT_MARKED				162
#define			IDI_QUIT_PRESSED			163

#define			IDI_EXP_SELECTROOT			164
#define			IDI_EXP_ADDFILE				165
#define			IDI_EXP_ADDFOLDER			166
#define			IDI_EXP_COPYELEMENT			167
#define			IDI_EXP_INSERTELEMENT		168
#define			IDI_EXP_DELETEELEMENT		169
#define			IDI_EXP_CONVERTELEMENT		170
#define			IDI_EXP_IMPORTCONTENT		171
#define			IDI_EXP_SEARCHFILE			172

#define			IDI_EXP_SELECTROOT_DISABLED			173
#define			IDI_EXP_ADDFILE_DISABLED			174
#define			IDI_EXP_ADDFOLDER_DISABLED			175
#define			IDI_EXP_COPYELEMENT_DISABLED		176
#define			IDI_EXP_INSERTELEMENT_DISABLED		177
#define			IDI_EXP_DELETEELEMENT_DISABLED		178
#define			IDI_EXP_CONVERTELEMENT_DISABLED		179
#define			IDI_EXP_IMPORTCONTENT_DISABLED		180
#define			IDI_EXP_SEARCHFILE_DISABLED			181

// ...
#define			IDI_EXP_RENAMEFILE			185
#define			IDI_EXP_RENAMEFILE_DISABLED	186

#define			IDI_SMP_INSERTSAMPLE		187
#define			IDI_SMP_INSERTSAMPLE_DISABLED 188

///////////////////////////////////////////////
#define			IDI_TV_CNC3					190
#define			IDI_TV_FILE					191
#define			IDI_TV_FOLDEROPENED			192
#define			IDI_TV_FOLDERCLOSED			193
#define			IDI_TV_NOCONTENT			194
#define			IDI_FN_SEARCH				195
#define			IDI_FN_OPENFOLDER			196
#define			IDI_SEARCH					197
#define			IDI_FIND					198
#define			IDI_OPENRESULT				199
///////////////////////////////////////////////
//#define			IDB_BKGND_UPPERLEFT_BLACK	200
//#define			IDB_BKGND_UPPERRIGHT_BLACK	201

#define			IDI_MAXIMIZE				202
#define			IDI_MAXIMIZE_MARKED			203
#define			IDI_MAXIMIZE_PRESSED		204
#define			IDI_MAXIMIZE_MIN			205
#define			IDI_MAXIMIZE_MARKED_MIN		206
#define			IDI_MAXIMIZE_PRESSED_MIN	207
#define			IDI_MINIMIZE				208
#define			IDI_MINIMIZE_MARKED			209
#define			IDI_MINIMIZE_PRESSED		210

#define			IDI_CNC3_FILEICON_SQ32		211
#define			IDI_TC_TABMENU_RESET		212
#define			IDI_TC_TABMENU_EXPAND		213
#define			IDI_TC_TABMENU_COPYTOTAB	214
#define			IDI_TC_TABMENU_OPENINWIN	215
#define			IDI_TC_TABMENU_ADDASTEMPL	216

#define			IDC_CNC3CURSOR				250
#define			IDC_FILECURSOR				251
#define			IDC_FOLDERCURSOR			252
#define			IDC_FORBIDDEN				253
#define			IDC_INSERT					254
#define			IDC_SAMPLE					255

#define			IDI_SC_CNC3					260

#define			IDI_CBOX_ERROR				265
#define			IDI_CBOX_WARNING			266
#define			IDI_CBOX_INFORMATION		267

#define			IDI_TC_CLOSERED				270
#define			IDI_TC_CLOSEGREEN			271
#define			IDI_TC_CLOSEMARKED			272

#define			IDI_WKI_ORANGE_DOT			273
#define			IDI_WKI_BLUE_DOT			274

#define			IDB_SPLASHSCREEN			280

//#define			IDB_BKGND_UPPERLEFT_GREEN	290
//#define			IDB_BKGND_UPPERRIGHT_GREEN	291
//#define			IDB_TITLEBAR_GREEN			292
//#define			IDB_BKGND_UPPERLEFT_DARKGRAY	293
//#define			IDB_BKGND_UPPERRIGHT_DARKGRAY	294
//#define			IDB_TITLEBAR_DARKGRAY		295
//#define			IDB_BKGND_UPPERLEFT_GRAY	296
//#define			IDB_BKGND_UPPERRIGHT_GRAY	297
//#define			IDB_TITLEBAR_GRAY			298


// STRING RESOURCE >>
#define			IDS_APPLICATIONCLASS		300
#define			IDS_APPLICATIONNAME			301
// MENU ID'S >>

// start type::button
#define			IDM_APPSETTINGS				401
#define			IDM_CLOSE					402
#define			IDM_MAXIMIZE				403
#define			IDM_MINIMIZE				404
#define			IDM_NEW						405
#define			IDM_OPEN					406
#define			IDM_SAVE					407
#define			IDM_SAVEALL					408
#define			IDM_SAVEAS					409
#define			IDM_IMPORT					410
#define			IDM_EXPORT					411
#define			IDM_COPY					412
#define			IDM_PASTE					413
#define			IDM_CUT						414
#define			IDM_SELECTALL				415
#define			IDM_EDITDELETE				416
#define			IDM_SEND					417
#define			IDM_RECEIVE					418
// end for iteration of tbbuttons!
#define			TBBUTTON_END				419

#define			IDM_HELP					420
#define			IDM_WEB						421
#define			IDM_QUIT					422
#define			IDM_HISTORY					423

#define			IDM_TOOLBAR_DROPDOWN		449
#define			ID_LASTBUTTON				450
// end of type::button

#define			ID_STATUSBAR				451
#define			ID_PROPERTYWINDOW			452
#define			ID_TVFRAME					453
#define			ID_TABCTRLFRAME				454
#define			ID_CBOXFRAME				455
#define			ID_SIZEBEAM					456

#define			ID_FILENAVIGATOR			460
#define			ID_CBOX						461
#define			ID_WORKINGINDICATOR			462
#define			ID_SAMPLEMANAGER			463

// searchwindow menu ids
#define			IDM_SEARCHMENU_G			470
#define			IDM_SEARCHMENU_E			471

#define			IDM_SEARCHSETTINGS			475
#define			IDM_SEARCHCLOSE				476

// data exchange window menu ids
#define			IDM_S_CONFIG_MENU_G			480
#define			IDM_S_CONFIG_MENU_E			481

#define			IDM_DEX_RESET				482
#define			IDM_DEX_CLOSE				483


// external commands
#define			NAVIGATOR_SETCURRENTFOLDER	500
#define			NAVIGATOR_RQ_OPENPATH		501
#define			NAVIGATOR_FILEWASCONVERTED	502
#define			NAVIGATOR_RQ_IMPORTFILE		503
//#define			NAVIGATOR_FILEWASDELETED	504
//#define			NAVIGATOR_FILEWASRENAMED	505

// icon ID's (continuing)
#define			IDI_EDITTOOLBAR_UPPERCASE_RED			600
#define			IDI_EDITTOOLBAR_UPPERCASE_GREEN			601
#define			IDI_EDITTOOLBAR_AUTOCOMPLETE_RED		602
#define			IDI_EDITTOOLBAR_AUTOCOMPLETE_GREEN		603
#define			IDI_EDITTOOLBAR_AUTONUM_RED				604
#define			IDI_EDITTOOLBAR_AUTONUM_GREEN			605
#define			IDI_EDITTOOLBAR_TEXTCOLOR_RED			606
#define			IDI_EDITTOOLBAR_TEXTCOLOR_GREEN			607
#define			IDI_EDITTOOLBAR_FOCUSMARK_RED			608
#define			IDI_EDITTOOLBAR_FOCUSMARK_GREEN			609
#define			IDI_EDITTOOLBAR_SHOWDESC				610
#define			IDI_EDITTOOLBAR_HIDEDESC				611
#define			IDI_EDITTOOLBAR_NUMSEQUENCE				612
#define			IDI_EDITTOOLBAR_RECONVERT				613
#define			IDI_EDITTOOLBAR_ERRORCHECK				614
#define			IDI_EDITTOOLBAR_AUTOSYNTAX				615
#define			IDI_EDITTOOLBAR_TEXTPROPERTIES			616
#define			IDI_S_CONFIG							617
#define			IDI_EXPAND_WND							618
#define			IDI_IMPAND_WND							619
#define			IDI_SYNC								620
#define			IDI_SMP_ADDSAMPLE						621
#define			IDI_SMP_ADDFILTER						622
#define			IDI_SMP_REMOVEELEMENT					623
#define			IDI_SMP_CLOSEMANAGER					624
#define			IDI_SMP_TV_FOLDEROPEN					625
#define			IDI_SMP_TV_FOLDERCLOSED					626
#define			IDI_SMP_TV_SAMPLEFILE					627
#define			IDI_SMP_SAVESAMPLE						628
#define			IDI_SMP_CHANGEELEMENT					629
#define			IDI_SMP_COPYTOCLIPBOARD					631
#define			IDI_SMP_TV_FOLDEROPEN_SEL				633
#define			IDI_SMP_TV_FOLDERCLOSED_SEL				634
#define			IDI_SMP_TV_SAMPLEFILE_SEL				635
#define			IDI_GNRL_CANCEL_YELLOW					636
#define			IDI_PROP_SETTINGS						637
#define			IDI_PROP_TABCTRL						638
#define			IDI_PROP_FILENAV						639
#define			IDI_PROP_EDITOR							640
#define			IDI_PROP_EXCHANGE						641
#define			IDI_PROP_INFO							642
#define			IDI_PROPCHECKBOX_CHECKED				643
#define			IDI_PROPCHECKBOX_UNCHECKED				644
#define			IDI_PROPCHECKBOX_CHECKED_DISABLED		645
#define			IDI_PROPCHECKBOX_UNCHECKED_DISABLED		646
#define			IDI_PROP_UPDATEARROWS					647
#define			IDI_PROP_UPDATEARROWS_DSBL				648
#define			IDI_PROP_CHOOSECOLOR					649
#define			IDI_GNRL_ADD_CROSS_WHITE				650
#define			IDI_GNRL_LOADRUNNER_BLUE				651
#define			IDI_WKI_MOVER_SQ5_BLUE					652
#define			IDI_WKI_MOVER_SQ5_ORANGE				653
#define			IDI_TCVT_UNDO							654
#define			IDI_TCVT_REDO							655
#define			IDI_HELPMARK							656
#define			IDI_HELPMARK_MARKED						657
#define			IDI_HELPMARK_PRESSED					658
#define			IDI_DESCTOOLBAR_DELETE					659
#define			IDI_DESCTOOLBAR_COPY					660
#define			IDI_DESCTOOLBAR_INSERT					661
#define			IDI_PROPRADIOBUTTON_CHECKED				662
#define			IDI_PROPRADIOBUTTON_UNCHECKED			663
#define			IDI_GNRL_BACK							664
#define			IDI_GNRL_ADD_CROSS_GREEN				665
#define			IDI_GNRL_DELETE_BIN						666
#define			IDI_PROP_SCEMEMANAGER					667
#define			IDI_PROP_AUTOCOMPLETEMANAGER			668
#define			IDI_TRACKBARBUTTON_NORMAL				669
#define			IDI_TRACKBARBUTTON_PRESSED				670
#define			IDI_CNC3_FILEICON_SQ32_MARK				671
#define			IDI_CNC3_FILEICON_SQ32_DSBL				672

#define			IDI_SYS_SCROLLARROW_UP					673
#define			IDI_SYS_SCROLLARROW_DOWN				674
#define			IDI_SYS_SCROLLARROW_LEFT				675
#define			IDI_SYS_SCROLLARROW_RIGHT				676

#define			IDI_SYS_SCROLLARROW_UP_HGL				677
#define			IDI_SYS_SCROLLARROW_DOWN_HGL			678
#define			IDI_SYS_SCROLLARROW_UP_PRS				679
#define			IDI_SYS_SCROLLARROW_DOWN_PRS			680

#define			IDI_SYS_SCROLLARROW_UP_DSBL				681
#define			IDI_SYS_SCROLLARROW_DOWN_DSBL			682

#define			IDI_SYS_SCROLLARROW_LEFT_HGL			683
#define			IDI_SYS_SCROLLARROW_RIGHT_HGL			684
#define			IDI_SYS_SCROLLARROW_LEFT_PRS			685
#define			IDI_SYS_SCROLLARROW_RIGHT_PRS			686

#define			IDI_SYS_SCROLLARROW_LEFT_DSBL			687
#define			IDI_SYS_SCROLLARROW_RIGHT_DSBL			688

#define			IDI_GNRL_ARROW_UP						689

#define			IDI_HISTORY								691
#define			IDI_HISTORY_MARKED						692
#define			IDI_HISTORY_PRESSED						693



//#define			IDI_MAINBUTTON_100						671
//#define			IDI_MAINBUTTON_125						672
//#define			IDI_MAINBUTTON_150						673
//#define			IDI_MAINBUTTON_175						674
//#define			IDI_MAINBUTTON_200						675
//
//#define			IDI_MAINBUTTON_100_MARKED				676
//#define			IDI_MAINBUTTON_125_MARKED				677
//#define			IDI_MAINBUTTON_150_MARKED				678
//#define			IDI_MAINBUTTON_175_MARKED				679
//#define			IDI_MAINBUTTON_200_MARKED				680
//
//#define			IDI_MAINBUTTON_100_PRESSED				681
//#define			IDI_MAINBUTTON_125_PRESSED				682
//#define			IDI_MAINBUTTON_150_PRESSED				683
//#define			IDI_MAINBUTTON_175_PRESSED				684
//#define			IDI_MAINBUTTON_200_PRESSED				685

//// FONTS >>
//#define			IDF_PROFONTWINDOWS						680
//#define			IDF_CODENEWROMAN						681
//#define			IDF_INCONSOLATA							682
//#define			IDF_COURIERPRIMECODE					683
//#define			IDF_COURIERPRIMESANS					684
//#define			IDF_VERAMONO							685
//#define			IDF_SVBASICMANUAL						686
//#define			IDF_PTMONO								687


//DIALOGRESOURCES
#define			IDD_SETUPDIALOG_G			700
#define			IDD_SETUPDIALOG_E			702
#define			ID_SRCHCKBX1				720
#define			ID_SRCHCKBX2				721
#define			ID_SRCHCKBX3				722
#define			ID_SRCHCKBX4				723
#define			ID_SRCHCKBX5				724
#define			ID_SRCHCKBX6				725
#define			ID_SRCHCKBX7				726
#define			ID_SRCHCKBX8				727

// TAB ID'S >>
#define			TAB_ID_START				800
// 801 - 830 Reserved for Tabs !!
/////////////////////////////////////////////////////////////////////////
// TAB-EDIT ID'S >>
#define			TABEDIT_ID_START			850
// 851 - 880 Reserved for Tab-edit-ids !!
/////////////////////////////////////////////////////////////////////////

// BACKGROUND IMAGES >>
//#define		IDB_BKGND_UPPERLEFT_BLACK_100	900
//#define		IDB_BKGND_UPPERLEFT_BLACK_125	901
//#define		IDB_BKGND_UPPERLEFT_BLACK_150	902
//#define		IDB_BKGND_UPPERLEFT_BLACK_175	903
//#define		IDB_BKGND_UPPERLEFT_BLACK_200	904
//
//#define		IDB_BKGND_UPPERLEFT_DARKGREY_100	905
//#define		IDB_BKGND_UPPERLEFT_DARKGREY_125	906
//#define		IDB_BKGND_UPPERLEFT_DARKGREY_150	907
//#define		IDB_BKGND_UPPERLEFT_DARKGREY_175	908
//#define		IDB_BKGND_UPPERLEFT_DARKGREY_200	909
//
//#define		IDB_BKGND_UPPERLEFT_LIGHTGREY_100	910
//#define		IDB_BKGND_UPPERLEFT_LIGHTGREY_125	911
//#define		IDB_BKGND_UPPERLEFT_LIGHTGREY_150	912
//#define		IDB_BKGND_UPPERLEFT_LIGHTGREY_175	913
//#define		IDB_BKGND_UPPERLEFT_LIGHTGREY_200	914
//
//#define		IDB_BKGND_UPPERLEFT_GREEN_100		915
//#define		IDB_BKGND_UPPERLEFT_GREEN_125		916
//#define		IDB_BKGND_UPPERLEFT_GREEN_150		917
//#define		IDB_BKGND_UPPERLEFT_GREEN_175		918
//#define		IDB_BKGND_UPPERLEFT_GREEN_200		919
//
//#define		IDB_BKGND_UPPERRIGHT_BLACK_100		920
//#define		IDB_BKGND_UPPERRIGHT_BLACK_125		921
//#define		IDB_BKGND_UPPERRIGHT_BLACK_150		922
//#define		IDB_BKGND_UPPERRIGHT_BLACK_175		923
//#define		IDB_BKGND_UPPERRIGHT_BLACK_200		924
//
//#define		IDB_BKGND_UPPERRIGHT_DARKGREY_100	925
//#define		IDB_BKGND_UPPERRIGHT_DARKGREY_125	926
//#define		IDB_BKGND_UPPERRIGHT_DARKGREY_150	927
//#define		IDB_BKGND_UPPERRIGHT_DARKGREY_175	928
//#define		IDB_BKGND_UPPERRIGHT_DARKGREY_200	929
//
//#define		IDB_BKGND_UPPERRIGHT_LIGHTGREY_100	930
//#define		IDB_BKGND_UPPERRIGHT_LIGHTGREY_125	931
//#define		IDB_BKGND_UPPERRIGHT_LIGHTGREY_150	932
//#define		IDB_BKGND_UPPERRIGHT_LIGHTGREY_175	933
//#define		IDB_BKGND_UPPERRIGHT_LIGHTGREY_200	934
//
//#define		IDB_BKGND_UPPERRIGHT_GREEN_100		935
//#define		IDB_BKGND_UPPERRIGHT_GREEN_125		936
//#define		IDB_BKGND_UPPERRIGHT_GREEN_150		937
//#define		IDB_BKGND_UPPERRIGHT_GREEN_175		938
//#define		IDB_BKGND_UPPERRIGHT_GREEN_200		939
//
//#define		IDB_BKGND_MID_BLACK_100				940
//#define		IDB_BKGND_MID_BLACK_125				941
//#define		IDB_BKGND_MID_BLACK_150				942
//#define		IDB_BKGND_MID_BLACK_175				943
//#define		IDB_BKGND_MID_BLACK_200				944
//
//#define		IDB_BKGND_MID_DARKGREY_100			945
//#define		IDB_BKGND_MID_DARKGREY_125			946
//#define		IDB_BKGND_MID_DARKGREY_150			947
//#define		IDB_BKGND_MID_DARKGREY_175			948
//#define		IDB_BKGND_MID_DARKGREY_200			949
//
//#define		IDB_BKGND_MID_LIGHTGREY_100			950
//#define		IDB_BKGND_MID_LIGHTGREY_125			951
//#define		IDB_BKGND_MID_LIGHTGREY_150			952
//#define		IDB_BKGND_MID_LIGHTGREY_175			953
//#define		IDB_BKGND_MID_LIGHTGREY_200			954
//
//#define		IDB_BKGND_MID_GREEN_100				955
//#define		IDB_BKGND_MID_GREEN_125				956
//#define		IDB_BKGND_MID_GREEN_150				957
//#define		IDB_BKGND_MID_GREEN_175				958
//#define		IDB_BKGND_MID_GREEN_200				959




