#pragma once
// Resource ID is invalid:
#define				_RESOURCE_INVALID					L"Error resource not found\0"

// English stringtable for CnC Suite:

// USERINTERFACE STRINGS >>
#define				_UI_FILENAVIGATOR					L"Filenavigator\0"
#define				_UI_APPPROPERTIES					L"Settings\0"
#define				_UI_TABCONTROL						L"Tab manager\0"
#define				_UI_SAMPLEMANAGER					L"Template-Manager\0"


#define				_UI_IMPORT_FILE_CONTENT				L"Import file content\0"
#define				_UI_IMPORT_ACTION					L"Import\0"
#define				_UI_DATAEXCHANGE_FINALIZE			L"Transfer to Tab\0"
#define				_UI_CANCEL							L"Cancel\0"
#define				_UI_DATAEXCHANGE_COMREADY			L"Terminal ready / waiting for data: \0"
#define				_UI_EDITCONTROL_SELECTIONRANGE		L"Selection range\0"
#define				_UI_EDITCONTROL_LINE				L"Line\0"
#define				_UI_EDITCONTROL_COLUMN				L"Column\0"
#define				_UI_TTP_SMPMNGR_ADDSAMPLE			L"Add new code template\0"
#define				_UI_TTP_SMPMNGR_ADDFILTER			L"Add new Filter\0"
#define				_UI_TTP_SMPMNGR_CHANGESAMPLE		L"Change template\0"
#define				_UI_TTP_SMPMNGR_REMOVESAMPLE		L"Remove selected element\0"
#define				_UI_TTP_SMPMNGR_COPYTOCLIPBOARD		L"Copy sample to clipboard\0"
#define				_UI_SMP_NEWFILTER_PLACEHOLDER		L"New filter\0"
#define				_UI_SMP_TEMPLATEFOLDER				L"Templates\0"	//obsolet!!!!!!!!!!
#define				_UI_SMP_SAMPLEFOLDER				L"Templates\0"
#define				_UI_SMP_REJECT						L"Reject\0"
#define				_UI_SMP_SAVESAMPLE					L"Save template\0"
#define				_UI_SMP_CHANGEELEMENT				L"Change element\0"
#define				_UI_SMP_INSERTSAMPLE				L"Insert template\0"
#define				_UI_SMP_CONFIRM_REMOVEFILTER		L"Confirm filter suspension.\0"
#define				_UI_SMP_CONFIRM_DELETESAMPLE		L"Finally remove template?\0"
#define				_UI_SMP_CAPTIONCONFIRMATION			L"Confirmation\0"
#define				_UI_SMP_MAXLEVELREACHED				L"The maximum of filterlevels is reached.\0"
#define				_UI_SMP_OVERRIDESAMPLE				L" already exists. Override?\0"

#define				_UI_GNRL_NAME						L"Name\0"
#define				_UI_GNRL_DESCRIPTION				L"Description\0"
#define				_UI_GNRL_CONTENT					L"Content\0"
#define				_UI_GNRL_NAMEINVALID				L"The name is not valid. These are forbidden literals:  < > : \" / \\ | * ? [ ] + , ; = % $\0"
#define				_UI_GNRL_COPYTOCLIPBOARD			L"Copy to clipboard\0"

#define				_UI_GNRL_ADDTAB						L"Add new tab (ctrl + N)\0"
#define				_UI_GNRL_OPEN						L"Open (ctrl + O)\0"
#define				_UI_GNRL_SAVE						L"Save (ctrl + S)\0"
#define				_UI_GNRL_SAVEAS						L"Save as...\0"
#define				_UI_GNRL_SAVEALL					L"Save all tabs (ctrl + shift + S)\0"
#define				_UI_GNRL_CUT						L"Cut (ctrl + X)\0"
#define				_UI_GNRL_COPY						L"Copy (ctrl + C)\0"
#define				_UI_GNRL_PASTE						L"Paste (ctrl + V)\0"
#define				_UI_GNRL_DELETE_SELECTEDTEXT		L"Delete selected text (del)\0"
#define				_UI_GNRL_SELECTALL					L"Select all (ctrl + A)\0"
#define				_UI_GNRL_SENDPROGRAM				L"Send program (ctrl + T)\0"
#define				_UI_GNRL_RECEIVEPROGRAM				L"Receive program (ctrl + R)\0"
#define				_UI_GNRL_IMPORT						L"Import file (ctrl + I)\0"
#define				_UI_GNRL_TEMPLATEMANAGER			L"Export as... (ctrl + M)\0"
#define				_UI_GNRL_APPLICATIONPROPERTIES		L"Settings\0"
#define				_UI_GNRL_NEWCNCFILE					L"New Program\0"
#define				_UI_GNRL_NEWFOLDER					L"New Folder\0"
#define				_UI_GNRL_COPYFOLDER					L"Copy Folder\0"
#define				_UI_GNRL_DELETE						L"Delete\0"
#define				_UI_GNRL_RENAME						L"Rename\0"
#define				_UI_GNRL_CONVERTTOCNC3				L"Convert to cnc3\0"
#define				_UI_GNRL_IMPORTCONTENT				L"Import Content\0"
#define				_UI_GNRL_COPYFILE					L"Copy File\0"
#define				_UI_GNRL_CHANGEROOTDIR				L"Change Root-Directory\0"
#define				_UI_GNRL_PASTEFILE					L"Paste\0"
#define				_UI_GNRL_OPENFILE					L"Open\0"
#define				_UI_GNRL_KEEPOLDFILE				L"Do you want to keep the old file?\0"
#define				_UI_GNRL_ADVANCED					L"Advanced Setup"
#define				_UI_GNRL_PLAIN_SAVE					L"Save"
#define				_UI_GNRL_NEWPROGRAM_PLACEHOLDER		L"New Program.cnc3"
#define				_UI_GNRL_NEWFOLDER_PLACEHOLDER		L"New Folder"
#define				_UI_GNRL_UNDO						L"Undo"
#define				_UI_GNRL_REDO						L"Redo"
#define				_UI_GNRL_OPENINNEWTAB				L"Open in new Tab"
#define				_UI_GNRL_PLAIN_OPEN					L"Open"
#define				_UI_GNRL_OPENHELP					L"Show Help"
#define				_UI_GNRL_VISITWEBSITE				L"Visit CnC-Suite Website"
#define				_UI_GNRL_CLOSEAPP					L"Close Application"
#define				_UI_GNRL_NAVIGATEBACK				L"\x2196  Back"
#define				_UI_GNRL_SHOWINWINEXPLORER			L"Show in Windows Explorer"
#define				_UI_GNRL_CANCEL						L"Cancel"
#define				_UI_GNRL_FINALIZE					L"Finalize"
#define				_UI_GNRL_INPUT						L"Input"
#define				_UI_GNRL_OUTPUT						L"Output"
#define				_UI_GNRL_CLOSE						L"Close"


#define				_UI_NAV_SEARCHINROOT				L"Search...\0"
#define				_UI_NAV_SELECTROOTFOLDER			L"Rootfolder...\0"
#define				_UI_NAV_EXPLORERBUTTON				L"Explorer"
#define				_UI_NAV_TEMPLATEBUTTON				L"Templates"

#define				_UI_EDITTOOLBAR_UPPERCASE			L"Uppercase (F1)\0"
#define				_UI_EDITTOOLBAR_LINENUMBERS			L"Auto-Linenumbers (F2)\0"
#define				_UI_EDITTOOLBAR_AUTOCOMPLETE		L"Autocomplete (F3)\0"
#define				_UI_EDITTOOLBAR_TEXTCOLOR			L"Textcolor (F4)\0"
#define				_UI_EDITTOOLBAR_MARKCOLOR			L"Line-Focus (F5)\0"
#define				_UI_EDITTOOLBAR_CONVERTALL			L"Re-format Code (F6)\0"
#define				_UI_EDITTOOLBAR_SEQUENCELINENBR		L"Re-sequence Linenumbers (F7)\0"
#define				_UI_EDITTOOLBAR_CHECKFORERROR		L"Scan program for syntaxerrors\0"
#define				_UI_EDITTOOLBAR_AUTOSYNTAX			L"Auto-Syntax Short-Settings\0"
#define				_UI_EDITTOOLBAR_TEXTPROPERTIES		L"Textproperties\0"
#define				_UI_EDITTOOLBAR_SHOWDOCPROPERTY		L"Show document-properties\0"
#define				_UI_EDITTOOLBAR_HIDEDOCPROPERTY		L"Hide document-properties\0"

#define				_UI_TABCTRL_DOCUMENTPROPERTIES		L"Document-Properties\0"
#define				_UI_TABCTRL_NEWTAB					L"New Tab\0"
#define				_UI_TABCTRL_DESCPLACEHOLDER_1		L"Drawing-Number\0"
#define				_UI_TABCTRL_DESCPLACEHOLDER_2		L"Customer/Customer ID\0"
#define				_UI_TABCTRL_DESCPLACEHOLDER_3		L"Description\0"
#define				_UI_TABCTRL_TTBUTTONCOPYDESC		L"Copy Properties to clipboard"
#define				_UI_TABCTRL_TTBUTTONINSERTDESC		L"Insert Properties"
#define				_UI_TABCTRL_TTBUTTONSETDIAMETER		L"Insert diameter-symbol"
#define				_UI_TABCTRL_TTBUTTONDELETEDESC		L"Erase all Properties"
#define				_UI_TABCTRL_FONTHEIGHT				L"Font Size"
#define				_UI_TABCTRL_LINEOFFSET				L"Line Spacing"
#define				_UI_TABCTRL_FONTBOLD				L"Bold"
#define				_UI_TABCTRL_EXPANDPATHTOFILE		L"Expand Path to File"
#define				_UI_TABCTRL_ERASETABCONTENT			L"Erase Tab"
#define				_UI_TABCTRL_COPYCONTENTTONEWTAB		L"Copy Content to new Tab"
#define				_UI_TABCTRL_SETCONTENTASTEMPLATE	L"Save as Standard-Template"

#define				_UI_PROPWND_SETTINGSBUTTON			L"General\0"
#define				_UI_PROPWND_TABCTRLBUTTON			L"Tab-Control\0"
#define				_UI_PROPWND_FILENAVIGATOR			L"File Explorer\0"
#define				_UI_PROPWND_EDITOR					L"Editor\0"
#define				_UI_PROPWND_EXCHANGE				L"Data Exchange\0"
#define				_UI_PROPWND_INFO					L"About\0"

#define				_UI_PROPWND_LANGUAGE				L"Language\0"
#define				_UI_PROPWND_SYSTEMLANGUAGE			L"Automatic\0"
#define				_UI_PROPWND_GERMAN					L"German\0"
#define				_UI_PROPWND_ENGLISH					L"English\0"
#define				_UI_PROPWND_DESIGN					L"Design\0"
#define				_UI_PROPWND_DSG_BLACK				L"Black\0"
#define				_UI_PROPWND_DSG_GREY				L"Grey\0"
#define				_UI_PROPWND_DSG_LIGHT				L"Light\0"
#define				_UI_PROPWND_DSG_GREEN				L"Green\0"
#define				_UI_PROPWND_AUTOUPDATESEARCH		L"Automatically"//L"Search for updates automatically\0"
#define				_UI_PROPWND_ACTIONONLAUNCH			L"Actions on App-Launch:\0"
#define				_UI_PROPWND_SAVEEXPLORERCOND		L"Restore file-explorer condition\0"
#define				_UI_PROPWND_SAVETABWNDCOND			L"Restore tabs and content\0"
#define				_UI_PROPWND_SAVEUNSAVEDCONTENT		L"Restore unsaved content\0"
#define				_UI_PROPWND_UPDATING				L"Update\0"
#define				_UI_PROPWND_SEARCHFORUPDATESNOW		L"Check now"//L"Check for Updates...\0"
#define				_UI_PROPWND_APPUPTODATE				L"\x2713 Up to date\0"
#define				_UI_PROPWND_UPDATEAVAILABLE			L"Update available\0"
#define				_UI_PROPWND_ERRORNOINTERNETCON		L"! No Internet Connection\0"
#define				_UI_PROPWND_AUTOSAVE				L"Save data automatically\0"
#define				_UI_PROPWND_OPENNEWFILEINNEWTAB		L"Always open files in new Tab\0"
#define				_UI_PROPWND_SHOWDOCPROPERTIES		L"Show document properties initially\0"
#define				_UI_PROPWND_DOCPROPTAGDESC			L"Document-property names\0"
#define				_UI_PROPWND_PROPDESCRIPTOR			L"Descriptor\0"
#define				_UI_PROPWND_ALWAYSEXPANDPATH		L"Always expand path to currently opened file"
#define				_UI_PROPWND_COLORSCHEME				L"Editor colorscheme"
#define				_UI_PROPWND_NORMAL					L"Normal"
#define				_UI_PROPWND_SEARCHFORERRORS			L"Search for syntax-errors automatically"
#define				_UI_PROPWND_AUTOCOMPLETESTRINGS		L"Autocomplete strings"
#define				_UI_PROPWND_EDITACSTRINGS			L"Edit autocomplete control..."
#define				_UI_PROPWND_ERRORCONTROL			L"Error detection"
#define				_UI_PROPWND_COMPORTNUMBER			L"COM Portnumber"
#define				_UI_PROPWND_BAUDRATE				L"Baudrate"
#define				_UI_PROPWND_PARITY					L"Parity"
#define				_UI_PROPWND_DATABITS				L"Databits"
#define				_UI_PROPWND_STOPBITS				L"Stopbits"

#define				_UI_PROPWND_NOPARITY				L"No parity"
#define				_UI_PROPWND_ODDPARITY				L"Odd parity"
#define				_UI_PROPWND_EVENPARITY				L"Even parity"
#define				_UI_PROPWND_MARKPARITY				L"Mark parity"
#define				_UI_PROPWND_SPACEPARITY				L"Space parity"
#define				_UI_PROPWND_FLOWCTRL_NONE			L"None"
#define				_UI_PROPWND_FLOWCTRL				L"Flowcontrol"
#define				_UI_PROPWND_FLOWCTRL_XONXOFF		L"Xon/Xoff"
#define				_UI_PROPWND_FLOWCTRL_HARDWARE		L"Hardware"
#define				_UI_PROPWND_PERFORMPARITYCHECK		L"Perform parity check"
#define				_UI_PROPWND_ABORTONERROR			L"Abort on error"
#define				_UI_PROPWND_REPLACEPARITYERROR		L"Replace error"
#define				_UI_PROPWND_DTRFLOWCONTROL			L"DTR Flowcontrol"
#define				_UI_PROPWND_RTSFLOWCONTROL			L"RTS Flowcontrol"
#define				_UI_PROPWND_CHARACTERS				L"Characters"
#define				_UI_PROPWND_INTERFACECONFIG			L"Interface Configuration"
#define				_UI_PROPWND_MANAGECOLORSCHEMES		L"Manage color schemes"
#define				_UI_PROPWND_CHOOSECOLOR				L"\xbb Choose color"
#define				_UI_PROPWND_NEWSCHEME				L"New color scheme"
#define				_UI_PROPWND_ANNOTATION				L"{ ( Annotation ) }"
#define				_UI_PROPWND_DEFAULTTEXTCOLOR		L"default text"
#define				_UI_PROPWND_LINENUMBERCOLOR			L"linenumber"
#define				_UI_PROPWND_BACKGROUNDCOLOR			L"background"
#define				_UI_PROPWND_RESETTEXTCOLOR			L"Reset textcolor"
#define				_UI_PROPWND_RESETBACKGROUND			L"Reset background"
#define				_UI_PROPWND_ADDAUTOCOMPL			L"Add new autocomplete string"
#define				_UI_PROPWND_DELETEAUTOCOMPL			L"Delete this string"
#define				_UI_PROPWND_WHENINSERT				L"When entering:"
#define				_UI_PROPWND_APPEND					L"Append:"
#define				_UI_PROPWND_PREVIEW					L"Preview:"
#define				_UI_PROPWND_OPENCREATEDFILE			L"Open created file in editor"
#define				_UI_PROPWND_USEFILETAGSASTOOLTIP	L"Show document-properties as tooltip"
#define				_UI_PROPWND_SEARCHSETTINGS			L"Search"
#define				_UI_PROPWND_SRCH_OPENMULTIFILE		L"Enable multi-file opening"
#define				_UI_PROPWND_SRCH_EXPANDPATH			L"Expand path to file in file-explorer"
#define				_UI_PROPWND_SRCH_CLOSEONOPEN		L"Close window after opening file(s)"
#define				_UI_PROPWND_SEARCHFORFILENAME		L"Filename"
#define				_UI_PROPWND_SEARCHFORFOLDERNAME		L"Foldername"
#define				_UI_PROPWND_SEARCH_IN				L"Search in..."
#define				_UI_PROPWND_AUTOSYNTAX				L"Autosyntax"
#define				_UI_PROPWND_SETAUTOSYNTAX			L"Set up Autosyntax"
#define				_UI_PROPWND_CONVERTSYNTAXONOPEN		L"Always keep syntax consistent"
#define				_UI_PROPWND_LINENUMBERS				L"Linenumbers"
#define				_UI_PROPWND_AUTONUMSTARTLINE		L"Line with first number"
#define				_UI_PROPWND_NUMSTEPMAIN				L"Main level linenumber step"
#define				_UI_PROPWND_NUMLENGTHMAIN			L"Main level linenumber lenght"
#define				_UI_PROPWND_MINIMUMLINENUMBER		L"Lowest linenumber"
#define				_UI_PROPWND_MAXIMUMLINENUMBER			L"Hightest linenumber"
#define				_UI_PROPWND_ERASELINENRONBACKSPACE			L"Erase complete linenumber with backspace key"
#define				_UI_PROPWND_NOSPACEINLINENUMBER				L"Use no spaces in linenumbers"
#define				_UI_PROPWND_USEDIFFERENTLINENUMBERINSUB		L"Use different linenumbers in sub-program"
#define				_UI_PROPWND_NUMLENGTHSUB					L"Sub level linenumber length"
#define				_UI_PROPWND_NUMSTEPSUB						L"Sub level linenumber step"
#define				_UI_PROPWND_NEWEVENLINENUMBERRONTRIGGER		L"New even linenumber on specific trigger"
#define				_UI_PROPWND_ENDPROGDETECTION				L"End-of-program detection"
#define				_UI_PROPWND_USEENDPROGDETECTION				L"Use End-of-program detection"
#define				_UI_PROPWND_ANNOTATIONANDVARIABLESTATEMENTS	L"Annotations and variable-statements"
#define				_UI_PROPWND_AUTOCOMPLETEBRACKETS			L"Autocomplete brackets"
#define				_UI_PROPWND_INSERTSPACESINAUTOCMPLTBARCKET	L"do not insert spaces in brackets"
#define				_UI_PROPWND_USEMULTILINEANNOTATIONS			L"Allow multiline annotations"
#define				_UI_PROPWND_SUBPROGDETECTION				L"Sub-program detection"
#define				_UI_PROPWND_TRIGGER							L"Trigger"
#define				_UI_PROPWND_PROGRAMRESTARTNECCESSARY		L"Program-restart required"

#define				_UI_PROPWND_STANDARDTEMPLATE				L"Standard-Template"
#define				_UI_PROPWND_INSERTSTANDARDTEMPLATE			L"Insert standard-template in \"New Tab\""
#define				_UI_PROPWND_CREATEDEVICELISTING				L"Find Serial Devices..."
#define				_UI_PROPWND_SELECTDEVICE					L"Select Device"
#define				_UI_PROPWND_FOUNDDEVICES					L"Devices found in the System:"
#define				_UI_PROPWND_NODEVICESELECTED				L"No Device selected."
#define				_UI_PROPWND_OUTPUTSETTINGS					L"Input/Output-Settings"
#define				_UI_PROPWND_OUTWINDOWSETTINGS				L"Input/Output-Window"
#define				_UI_PROPWND_OUTFORMATSETTINGS				L"Output-Format"
#define				_UI_PROPWND_ANCHOROUTPUTWINDOW				L"Anchor Transmission-Window"
#define				_UI_PROPWND_MONITORTRANSMISSON				L"Monitor Transmission"
#define				_UI_PROPWND_VERBOSETRANSMISSION				L"Verbose"
#define				_UI_PROPWND_AUTOCLOSE						L"Autoclose"
#define				_UI_PROPWND_RESETBUTTON						L"Reset Application (completely or partially)"
#define				_UI_PROPWND_DISCREET						L"Discreet"
#define				_UI_PROPWND_DELETECURRENTSCHEME				L"Delete the selected Colorscheme."
#define				_UI_PROPWND_REMOVEAPOSTROPHECOMMENT			L"Remove Annotations (introduced with: ; )"
#define				_UI_PROPWND_REMOVEBRACKETCOMMENT			L"Remove Bracket Annotations (...)  {...}"
#define				_UI_PROPWND_REMOVESPACES					L"Remove Spaces"

#define				_UI_EXPLORER_TOOLTIP_LOADROOTFOLDER			L"Select Root-Folder"
#define				_UI_EXPLORER_TOOLTIP_NEWPROGRAMM			L"Add new nc-program to selected folder"
#define				_UI_EXPLORER_TOOLTIP_NEWFOLDER				L"Add new sub-folder to selected directory"
#define				_UI_EXPLORER_TOOLTIP_COPYELEMENT			L"Copy selected element"
#define				_UI_EXPLORER_TOOLTIP_INSERTELEMENT			L"Insert element in selected directory"
#define				_UI_EXPLORER_TOOLTIP_DELETEELEMENT			L"Delete selected element"
#define				_UI_EXPLORER_TOOLTIP_CONVERTTOCNC3			L"Convert element to cnc3 file"
#define				_UI_EXPLORER_TOOLTIP_IMPORTCONTENT			L"Import content of selected file"
#define				_UI_EXPLORER_TOOLTIP_SEARCHFORPROGRAMM		L"Search for nc-programs"

#define				_UI_SSCREEN_LOADING					L"Loading..."
#define				_UI_SSCREEN_INITAPPDATA				L"Initalizing application data"
#define				_UI_SSCREEN_VERIFYFILESYSTEM		L"Verifying filesystem"
#define				_UI_SSCREEN_LOADEDITRESOURCES		L"Initalizing editor resources"
#define				_UI_SSCREEN_INITMAINFRAME			L"Loading Userinterface"

#define				_UI_STATUSBAR_READY_STATE			L"Ready"
#define				_UI_STATUSBAR_SENDINPROGRESS		L"Sending data ..."
#define				_UI_STATUSBAR_RECEIVEINPROGRESS		L"Receiving data ..."

#define				_UI_PROGRESS_COLLECTINGDATA			L"Collecting data ..."
#define				_UI_PROGRESS_LOADINGDATA			L"Loading data ..."

#define				_UI_SEARCHCTRL_MAXSRCHRESULT		L"More than 300 results..."

#define				_UI_RESETWND_CHOOSECOMPONENT		L"Select Components:"
#define				_UI_RESETWND_COMPARAMETER			L"COM Interface Settings"
#define				_UI_RESETWND_COMMONSETTINGS			L"CnC Suite Settings"
#define				_UI_RESETWND_AUTOSYNTAXSETUP		L"Autosyntax Settings"
#define				_UI_RESETWND_USERTEXT				L"Userdefined Text"
#define				_UI_RESETWND_INTERNALSETUP			L"Internal Settings"
#define				_UI_RESETWND_AUTOCOMPLETESETUP		L"Autocomplete Data"
#define				_UI_RESETWND_APPDATA				L"Application Data"
#define				_UI_RESETWND_SESSIONDATA			L"Session Data"
#define				_UI_RESETWND_RESTARTMESSAGE			L"The Application must be relaunched."

#define				_UI_PROPWND_SAVEHISTORY				L"Generate chronicle"
#define				_UI_PROPWND_DELETEHISTORYNOW		L"Reset chronicle"

#define				_UI_GNRL_COPYRIGHT					L"\xa9 2018 LaroomySoft"
#define				_UI_GNRL_RIGHTS						L"All Rights reserved."
#define				_UI_GNRL_USERCANCELCONFIRM			L"Is canceled..."
#define				_UI_GNRL_NEWSUBFOLDER				L"New Sub-Folder"
#define				_UI_GNRL_LINEENDFORMAT				L"End of Line:"
#define				_UI_GNRL_HISTORY					L"Chronicle"

#define				_UI_FILETIME_CREATED				L"Created:      "
#define				_UI_FILETIME_LASTWRITE				L"Last modified:"
#define				_UI_FILETIME_LASTACCESS				L"Last accessed:"
#define				_UI_FILEINFO						L"File"
#define				_UI_FILESIZE						L"Filesize:     "

// ERROR MESSAGES >>

#define				_UI_XML_ERR_UNEXPECTEDCLOSINGTAG	L"XML-Syntaxerror: unexpected closing-tag  Index: \0"
#define				_UI_XML_ERR_DOCUMENTFORMAT_INVALID	L"XML-error: documentformat invalid\0"
#define				_UI_XML_ERR_NOCLOSING_ELEMENT_P1	L"XML-Syntaxerror: closing element for \"\0"
#define				_UI_XML_ERR_NOCLOSING_ELEMENT_P2	L"\" not found. Index: \0"

#define				_ERROR_MSG_FILETYPE_NOTSUPPORTED	L"Filetype not supported. Please use the import-function to display foreign data.\0"
#define				_ERROR_MSG_ROOTFOLDERINVALIDATED	L"The current Root-Folder has become invalid. Please select a new Folder."
#define				_ERROR_MSG_ROOTFOLDERLOADINGFAILED	L"(E_UNEXPECTED) Loading Root-Folder failed."
#define				_ERROR_MSG_DRIVELOADINGNOTALLOWED	L"A complete Drive cannot be loaded. Please select a sub-Folder."

// WARNINGS >>
#define				_WARNING_MSG_UPDATESEARCH_FAILED	L"Search for updates failed - no internet connection.\0"
#define				_WARNING_MSG_SAVEALL_NOPATHFOUND	L"Target-path missing for one or more tabs."

// INFORMATION >>
#define				_INFO_MSG_FILEWASIMPORTED			L"Autoimport successful executed for file: \0"
#define				_INFO_MSG_FILEWASCONVERTED			L"Fileconversion succesful executed for file: \0"
#define				_INFO_MSG_UPDATEAVAILABLE			L"An update is available.\0"
#define				_INFO_MSG_LASTTABNOCLOSE			L"Last tab cannot be closed.\0"
#define				_INFO_MSG_MAXIMUMTABCOUNTREACHED	L"Tab-maximum is reached.\0"
#define				_INFO_MSG_FILEISALREADYOPEN			L"File is already open."
#define				_INFO_MSG_CHANGESNEEDRESTART		L"An application-restart is required to apply the requested changes."
#define				_INFO_MSG_NOTARGETSELECTED			L"No Target selected"

// DIALOG STRINGS >>
#define				_DLG_MSG_FILENOTSAVEDSAVENOW		L" is not saved. Save now?\0"
#define				_DLG_MSG_UNSAVEDCONTENTEXISTS		L" tabs contain unsaved content. Close anyway?\0"