#pragma once
// Resource ID is invalid:
#define				_RESOURCE_INVALID					L"Fehler Resource nicht gefunden\0"

// German stringtable for CnC Suite:

// USERINTERFACE STRINGS >>
#define				_UI_FILENAVIGATOR					L"Dateimanager\0"
#define				_UI_APPPROPERTIES					L"Einstellungen\0"
#define				_UI_TABCONTROL						L"Tab Manager\0"
#define				_UI_SAMPLEMANAGER					L"Ausschnitt Manager\0"


#define				_UI_IMPORT_FILE_CONTENT				L"Dateiinhalt importieren\0"
#define				_UI_IMPORT_ACTION					L"Importieren\0"
#define				_UI_DATAEXCHANGE_FINALIZE			L"In Tab übertragen\0"
#define				_UI_CANCEL							L"Abbrechen\0"
#define				_UI_DATAEXCHANGE_COMREADY			L"Terminal bereit / warte auf Daten: \0"
#define				_UI_EDITCONTROL_SELECTIONRANGE		L"Auswahl\0"
#define				_UI_EDITCONTROL_LINE				L"Zeile\0"
#define				_UI_EDITCONTROL_COLUMN				L"Spalte\0"
#define				_UI_TTP_SMPMNGR_ADDSAMPLE			L"Code Ausschnitt hinzufügen\0"
#define				_UI_TTP_SMPMNGR_ADDFILTER			L"Neuer Filter\0"
#define				_UI_TTP_SMPMNGR_CHANGESAMPLE		L"Ausschnitt ändern\0"
#define				_UI_TTP_SMPMNGR_REMOVESAMPLE		L"Element löschen\0"
#define				_UI_TTP_SMPMNGR_COPYTOCLIPBOARD		L"Ausschnitt in Zwischenablage kopieren\0"
#define				_UI_SMP_NEWFILTER_PLACEHOLDER		L"Neuer Filter\0"
#define				_UI_SMP_TEMPLATEFOLDER				L"Vorlagen\0"
#define				_UI_SMP_SAMPLEFOLDER				L"Ausschnitte\0"
#define				_UI_SMP_REJECT						L"Verwerfen\0"
#define				_UI_SMP_SAVESAMPLE					L"Ausschnitt speichern\0"
#define				_UI_SMP_CHANGEELEMENT				L"Element ändern\0"
#define				_UI_SMP_INSERTSAMPLE				L"Ausschnitt einfügen\0"
#define				_UI_SMP_CONFIRM_REMOVEFILTER		L"Filter wird aufgelöst?\0"
#define				_UI_SMP_CONFIRM_DELETESAMPLE		L"Ausschnitt endgültig löschen?\0"
#define				_UI_SMP_CAPTIONCONFIRMATION			L"Bestätigung\0"
#define				_UI_SMP_MAXLEVELREACHED				L"Das Maximum an Filter-Levels ist erreicht.\0"
#define				_UI_SMP_OVERRIDESAMPLE				L" existiert bereits. Überschreiben?\0"

#define				_UI_GNRL_NAME						L"Name\0"
#define				_UI_GNRL_DESCRIPTION				L"Beschreibung\0"
#define				_UI_GNRL_CONTENT					L"Inhalt\0"
#define				_UI_GNRL_NAMEINVALID				L"Der Name ist ungültig. Diese Zeichen sind verboten:  < > : \" / \\ | * ? [ ] + , ; = % $\0"
#define				_UI_GNRL_COPYTOCLIPBOARD			L"In die Zwischenablage kopieren\0"

#define				_UI_GNRL_ADDTAB						L"Neuen Tab hinzufügen (Strg + N)\0"
#define				_UI_GNRL_OPEN						L"Öffnen (Strg + O)\0"
#define				_UI_GNRL_SAVE						L"Speichern (Strg + S)\0"
#define				_UI_GNRL_SAVEAS						L"Speichern unter...\0"
#define				_UI_GNRL_SAVEALL					L"Alle Tabs speichern (Strg + Umschalt + S)\0"
#define				_UI_GNRL_CUT						L"Ausschneiden (Strg + X)\0"
#define				_UI_GNRL_COPY						L"Kopieren (Strg + C)\0"
#define				_UI_GNRL_PASTE						L"Einfügen (Strg + V)\0"
#define				_UI_GNRL_DELETE_SELECTEDTEXT		L"Ausgewählten Text löschen (Entf)\0"
#define				_UI_GNRL_SELECTALL					L"Alles auswählen (Strg + A)\0"
#define				_UI_GNRL_SENDPROGRAM				L"Programm senden (Strg + T)\0"
#define				_UI_GNRL_RECEIVEPROGRAM				L"Programm empfangen (Strg + R)\0"
#define				_UI_GNRL_IMPORT						L"Datei importieren (Strg + I)\0"
#define				_UI_GNRL_TEMPLATEMANAGER			L"Exportieren als... (Strg + M)\0"
#define				_UI_GNRL_APPLICATIONPROPERTIES		L"Einstellungen\0"
#define				_UI_GNRL_NEWCNCFILE					L"Neues Programm\0"
#define				_UI_GNRL_NEWFOLDER					L"Neuer Ordner\0"
#define				_UI_GNRL_COPYFOLDER					L"Ordner kopieren\0"
#define				_UI_GNRL_DELETE						L"Löschen\0"
#define				_UI_GNRL_RENAME						L"Umbenennen\0"
#define				_UI_GNRL_CONVERTTOCNC3				L"In cnc3 konvertieren\0"
#define				_UI_GNRL_IMPORTCONTENT				L"Inhalt importieren\0"
#define				_UI_GNRL_COPYFILE					L"Datei kopieren\0"
#define				_UI_GNRL_CHANGEROOTDIR				L"Stammordner wechseln\0"
#define				_UI_GNRL_PASTEFILE					L"Einfügen\0"
#define				_UI_GNRL_OPENFILE					L"Öffnen\0"
#define				_UI_GNRL_KEEPOLDFILE				L"Möchten Sie die alte Datei behalten?\0"
#define				_UI_GNRL_ADVANCED					L"Erweiterte Einstellungen"
#define				_UI_GNRL_PLAIN_SAVE					L"Speichern"
#define				_UI_GNRL_NEWPROGRAM_PLACEHOLDER		L"Neues Programm.cnc3"
#define				_UI_GNRL_NEWFOLDER_PLACEHOLDER		L"Neuer Ordner"
#define				_UI_GNRL_UNDO						L"Rückgängig"
#define				_UI_GNRL_REDO						L"Wiederholen"
#define				_UI_GNRL_OPENINNEWTAB				L"In neuem Tab öffnen"
#define				_UI_GNRL_PLAIN_OPEN					L"Öffnen"
#define				_UI_GNRL_OPENHELP					L"Hilfe öffnen"
#define				_UI_GNRL_VISITWEBSITE				L"CnC-Suite Website besuchen"
#define				_UI_GNRL_CLOSEAPP					L"Anwendung schließen"
#define				_UI_GNRL_NAVIGATEBACK				L"\x2196  Zurück"					//left arrow (calibri) \x2190
#define				_UI_GNRL_SHOWINWINEXPLORER			L"Im Windows Explorer anzeigen"
#define				_UI_GNRL_CANCEL						L"Abbrechen"
#define				_UI_GNRL_FINALIZE					L"Abschließen"
#define				_UI_GNRL_INPUT						L"Eingabe"
#define				_UI_GNRL_OUTPUT						L"Ausgabe"
#define				_UI_GNRL_CLOSE						L"Schließen"



#define				_UI_NAV_SEARCHINROOT				L"Suchen...\0"
#define				_UI_NAV_SELECTROOTFOLDER			L"Stammordner...\0"
#define				_UI_NAV_EXPLORERBUTTON				L"Explorer"
#define				_UI_NAV_TEMPLATEBUTTON				L"Templates"


#define				_UI_EDITTOOLBAR_UPPERCASE			L"Uppercase (F1)\0"
#define				_UI_EDITTOOLBAR_LINENUMBERS			L"Auto-Satznummern (F2)\0"
#define				_UI_EDITTOOLBAR_AUTOCOMPLETE		L"Autocomplete (F3)\0"
#define				_UI_EDITTOOLBAR_TEXTCOLOR			L"Textfarbe (F4)\0"
#define				_UI_EDITTOOLBAR_MARKCOLOR			L"Zeilenfokus (F5)\0"
#define				_UI_EDITTOOLBAR_CONVERTALL			L"Code neu formatieren (F6)\0"
#define				_UI_EDITTOOLBAR_SEQUENCELINENBR		L"Satznummern neu sequenzieren (F7)\0"
#define				_UI_EDITTOOLBAR_CHECKFORERROR		L"Programm nach Syntaxfehlern scannen\0"
#define				_UI_EDITTOOLBAR_AUTOSYNTAX			L"Auto-Syntax Schnell-Einstellungen\0"
#define				_UI_EDITTOOLBAR_TEXTPROPERTIES		L"Texteigenschaften\0"
#define				_UI_EDITTOOLBAR_SHOWDOCPROPERTY		L"Dokumenteigenschaften einblenden\0"
#define				_UI_EDITTOOLBAR_HIDEDOCPROPERTY		L"Dokumenteigenschaften ausblenden\0"

#define				_UI_TABCTRL_DOCUMENTPROPERTIES		L"Dokumenteigenschaften\0"
#define				_UI_TABCTRL_NEWTAB					L"Neuer Tab\0"
#define				_UI_TABCTRL_DESCPLACEHOLDER_1		L"Zeichnungsnummer\0"
#define				_UI_TABCTRL_DESCPLACEHOLDER_2		L"Kunde/Kundennummer\0"
#define				_UI_TABCTRL_DESCPLACEHOLDER_3		L"Beschreibung\0"
#define				_UI_TABCTRL_TTBUTTONCOPYDESC		L"Eigenschaften in Zwischenablage kopieren"
#define				_UI_TABCTRL_TTBUTTONINSERTDESC		L"Eigenschaften einfügen"
#define				_UI_TABCTRL_TTBUTTONSETDIAMETER		L"Durchmessersymbol einfügen"
#define				_UI_TABCTRL_TTBUTTONDELETEDESC		L"Alle Eigenschaften löschen"
#define				_UI_TABCTRL_FONTHEIGHT				L"Schriftgröße"
#define				_UI_TABCTRL_LINEOFFSET				L"Zeilenabstand"
#define				_UI_TABCTRL_FONTBOLD				L"Fett"
#define				_UI_TABCTRL_EXPANDPATHTOFILE		L"Pfad zur Datei expandieren"
#define				_UI_TABCTRL_ERASETABCONTENT			L"Tab zurücksetzen"
#define				_UI_TABCTRL_COPYCONTENTTONEWTAB		L"Tabinhalt in neuen Tab kopieren"
#define				_UI_TABCTRL_SETCONTENTASTEMPLATE	L"Als Standardvorlage speichern"


#define				_UI_PROPWND_SETTINGSBUTTON			L"Allgemein\0"
#define				_UI_PROPWND_TABCTRLBUTTON			L"Tab-Steuerung\0"
#define				_UI_PROPWND_FILENAVIGATOR			L"Datei Explorer\0"
#define				_UI_PROPWND_EDITOR					L"Editor\0"
#define				_UI_PROPWND_EXCHANGE				L"Datenaustausch\0"
#define				_UI_PROPWND_INFO					L"Info\0"

#define				_UI_PROPWND_LANGUAGE				L"Sprache\0"
#define				_UI_PROPWND_SYSTEMLANGUAGE			L"Automatisch\0"
#define				_UI_PROPWND_GERMAN					L"Deutsch\0"
#define				_UI_PROPWND_ENGLISH					L"Englisch\0"
#define				_UI_PROPWND_DESIGN					L"Design\0"
#define				_UI_PROPWND_DSG_BLACK				L"Schwarz\0"
#define				_UI_PROPWND_DSG_GREY				L"Dunkelgrau\0"
#define				_UI_PROPWND_DSG_LIGHT				L"Hellgrau\0"
#define				_UI_PROPWND_DSG_GREEN				L"Grün\0"
#define				_UI_PROPWND_AUTOUPDATESEARCH		L"Automatisch\0"
#define				_UI_PROPWND_ACTIONONLAUNCH			L"Aktionen bei Programmstart:\0"
#define				_UI_PROPWND_SAVEEXPLORERCOND		L"Zustand des Datei-Explorers wiederherstellen\0"
#define				_UI_PROPWND_SAVETABWNDCOND			L"Tabs und Inhalt wiederherstellen\0"
#define				_UI_PROPWND_SAVEUNSAVEDCONTENT		L"Ungespeicherten Inhalt wiederherstellen\0"
#define				_UI_PROPWND_UPDATING				L"Aktualisierung\0"
#define				_UI_PROPWND_SEARCHFORUPDATESNOW		L"Jetzt überprüfen"//L"Jetzt nach Updates suchen...\0"
#define				_UI_PROPWND_APPUPTODATE				L"\x2713 Aktuell\0"
#define				_UI_PROPWND_UPDATEAVAILABLE			L"Update verfügbar\0"
#define				_UI_PROPWND_ERRORNOINTERNETCON		L"! Keine Internetverbindung\0"
#define				_UI_PROPWND_AUTOSAVE				L"Automatisch speichern\0"
#define				_UI_PROPWND_OPENNEWFILEINNEWTAB		L"Dateien immer in neuem Tab öffnen\0"
#define				_UI_PROPWND_SHOWDOCPROPERTIES		L"Dokumenteigenschaften beim Start anzeigen\0"
#define				_UI_PROPWND_DOCPROPTAGDESC			L"Dokumenteigenschaften\0"
#define				_UI_PROPWND_PROPDESCRIPTOR			L"Descriptor\0"
#define				_UI_PROPWND_ALWAYSEXPANDPATH		L"Beim Öffnen Pfad zur Datei expandieren"
#define				_UI_PROPWND_COLORSCHEME				L"Editor Farbschema"
#define				_UI_PROPWND_NORMAL					L"Normal"
#define				_UI_PROPWND_SEARCHFORERRORS			L"Automatisch nach Syntaxfehlern suchen"
#define				_UI_PROPWND_AUTOCOMPLETESTRINGS		L"Autocomplete Zeichenfolgen"
#define				_UI_PROPWND_EDITACSTRINGS			L"Autocomplete bearbeiten..."
#define				_UI_PROPWND_ERRORCONTROL			L"Fehlerkorrektur"
#define				_UI_PROPWND_COMPORTNUMBER			L"COM Anschlussnummer"
#define				_UI_PROPWND_BAUDRATE				L"Baudrate"
#define				_UI_PROPWND_PARITY					L"Parität"
#define				_UI_PROPWND_DATABITS				L"Datenbits"
#define				_UI_PROPWND_STOPBITS				L"Stopbits"
#define				_UI_PROPWND_NOPARITY				L"Keine"
#define				_UI_PROPWND_ODDPARITY				L"Ungerade"
#define				_UI_PROPWND_EVENPARITY				L"Gerade"
#define				_UI_PROPWND_MARKPARITY				L"Markierung"
#define				_UI_PROPWND_SPACEPARITY				L"Leerzeichen"
#define				_UI_PROPWND_FLOWCTRL_NONE			L"Keine"
#define				_UI_PROPWND_FLOWCTRL				L"Flusssteuerung"
#define				_UI_PROPWND_FLOWCTRL_XONXOFF		L"Xon/Xoff"
#define				_UI_PROPWND_FLOWCTRL_HARDWARE		L"Hardware"
#define				_UI_PROPWND_PERFORMPARITYCHECK		L"Parität überprüfen"
#define				_UI_PROPWND_ABORTONERROR			L"Bei Fehler abbrechen"
#define				_UI_PROPWND_REPLACEPARITYERROR		L"Fehlerhaftes Zeichen ersetzen"
#define				_UI_PROPWND_DTRFLOWCONTROL			L"DTR Flusssteuerung"
#define				_UI_PROPWND_RTSFLOWCONTROL			L"RTS Flusssteuerung"
#define				_UI_PROPWND_CHARACTERS				L"Zeichen"
#define				_UI_PROPWND_INTERFACECONFIG			L"Schnittstellenkonfiguration"
#define				_UI_PROPWND_MANAGECOLORSCHEMES		L"Farbschema verwalten"
#define				_UI_PROPWND_CHOOSECOLOR				L"\xbb Farbe wählen"
#define				_UI_PROPWND_NEWSCHEME				L"Neue Farbgebung"
#define				_UI_PROPWND_ANNOTATION				L"{ ( Kommentar ) }"
#define				_UI_PROPWND_DEFAULTTEXTCOLOR		L"standard Text"
#define				_UI_PROPWND_LINENUMBERCOLOR			L"Satznummer"
#define				_UI_PROPWND_BACKGROUNDCOLOR			L"Hintergrund"
#define				_UI_PROPWND_RESETTEXTCOLOR			L"Textfarbe zurücksetzen"
#define				_UI_PROPWND_RESETBACKGROUND			L"Hintergrund zurücksetzen"
#define				_UI_PROPWND_ADDAUTOCOMPL			L"Neuen Autocomplete Satz hinzufügen"
#define				_UI_PROPWND_DELETEAUTOCOMPL			L"Diesen Satz löschen"
#define				_UI_PROPWND_WHENINSERT				L"Bei Eingabe von:"
#define				_UI_PROPWND_APPEND					L"Füge an:"
#define				_UI_PROPWND_PREVIEW					L"Vorschau:"
#define				_UI_PROPWND_OPENCREATEDFILE			L"Neu erzeugte Datei im Editor öffnen"
#define				_UI_PROPWND_USEFILETAGSASTOOLTIP	L"Dokumenteigenschaften als Tooltip anzeigen"
#define				_UI_PROPWND_SEARCHSETTINGS			L"Suche"
#define				_UI_PROPWND_SRCH_OPENMULTIFILE		L"Öffnen mehrerer Dateien erlauben"
#define				_UI_PROPWND_SRCH_EXPANDPATH			L"Pfad zur Datei im Dateiexplorer expandieren"
#define				_UI_PROPWND_SRCH_CLOSEONOPEN		L"Such-Fenster nach dem Öffnen der Datei(en) schließen"
#define				_UI_PROPWND_SEARCHFORFILENAME		L"Dateiname"
#define				_UI_PROPWND_SEARCHFORFOLDERNAME		L"Ordnername"
#define				_UI_PROPWND_SEARCH_IN				L"Suchen in..."
#define				_UI_PROPWND_AUTOSYNTAX				L"Autosyntax"
#define				_UI_PROPWND_SETAUTOSYNTAX			L"Autosyntax einstellen"
#define				_UI_PROPWND_CONVERTSYNTAXONOPEN		L"Syntax immer konsistent halten"
#define				_UI_PROPWND_LINENUMBERS				L"Satznummerierung"
#define				_UI_PROPWND_AUTONUMSTARTLINE		L"Zeile mit erster Satznummer"
#define				_UI_PROPWND_NUMSTEPMAIN				L"Sprungweite im Hauptprogramm"
#define				_UI_PROPWND_NUMLENGTHMAIN			L"Satznummerlänge im Hauptprogramm"
#define				_UI_PROPWND_MINIMUMLINENUMBER		L"Kleinste Satznummer"
#define				_UI_PROPWND_MAXIMUMLINENUMBER		L"Höchste Satznummer"

#define				_UI_PROPWND_ERASELINENRONBACKSPACE			L"Satznummer automatisch entfernen (backspace)"
#define				_UI_PROPWND_NOSPACEINLINENUMBER				L"Keine Leerzeichen in Satznummer erlauben"
#define				_UI_PROPWND_USEDIFFERENTLINENUMBERINSUB		L"Unterschiedliche Satznummern im Unterprogramm verwenden"
#define				_UI_PROPWND_NUMLENGTHSUB					L"Satznummerlänge im Unterprogramm"
#define				_UI_PROPWND_NUMSTEPSUB						L"Satznummerschritte im Unterprogramm"
#define				_UI_PROPWND_NEWEVENLINENUMBERRONTRIGGER		L"Neue runde Satznummer bei speziellem Auslöser"
#define				_UI_PROPWND_ENDPROGDETECTION				L"Programmende-Erkennung"
#define				_UI_PROPWND_USEENDPROGDETECTION				L"Aktiv"
#define				_UI_PROPWND_ANNOTATIONANDVARIABLESTATEMENTS	L"Kommentare und Variablenausdrücke"
#define				_UI_PROPWND_AUTOCOMPLETEBRACKETS			L"Klammern automatisch vervollständigen"
#define				_UI_PROPWND_INSERTSPACESINAUTOCMPLTBARCKET	L"Keine Leerzeichen einfügen"
#define				_UI_PROPWND_USEMULTILINEANNOTATIONS			L"Mehrzeilen-Kommentare erlauben"
#define				_UI_PROPWND_SUBPROGDETECTION				L"Unterprogramm-Erkennung"
#define				_UI_PROPWND_TRIGGER							L"Auslöser"
#define				_UI_PROPWND_PROGRAMRESTARTNECCESSARY		L"Programmneustart erforderlich"
#define				_UI_PROPWND_CONFIRMHISTORYDELETITION		L"Die gesamte Chronik wird gelöscht?"

#define				_UI_PROPWND_STANDARDTEMPLATE				L"Standard-Vorlage"
#define				_UI_PROPWND_INSERTSTANDARDTEMPLATE			L"Standard Vorlage in \"Neuen Tab\" einfügen"
#define				_UI_PROPWND_CREATEDEVICELISTING				L"Serielle Geräte suchen..."
#define				_UI_PROPWND_SELECTDEVICE					L"Gerät auswählen"
#define				_UI_PROPWND_FOUNDDEVICES					L"Im System vorhandene Geräte:"
#define				_UI_PROPWND_NODEVICESELECTED				L"Kein Gerät ausgewählt."
#define				_UI_PROPWND_OUTPUTSETTINGS					L"Ein-/Ausgabe-Einstellungen"
#define				_UI_PROPWND_OUTWINDOWSETTINGS				L"Ein-/Ausgabefenster"
#define				_UI_PROPWND_OUTFORMATSETTINGS				L"Ausgabeformat"
#define				_UI_PROPWND_ANCHOROUTPUTWINDOW				L"Ein-/Ausgabefenster andocken"
#define				_UI_PROPWND_MONITORTRANSMISSON				L"Ein-/Ausgabe überwachen (Monitor)"
#define				_UI_PROPWND_VERBOSETRANSMISSION				L"Ausführliche Ausgabe"
#define				_UI_PROPWND_AUTOCLOSE						L"Automatisch schließen"
#define				_UI_PROPWND_RESETBUTTON						L"Anwendung ganz oder teilweise zurücksetzen"
#define				_UI_PROPWND_DISCREET						L"Dezent"
#define				_UI_PROPWND_DELETECURRENTSCHEME				L"Ausgewähltes Schema löschen."
#define				_UI_PROPWND_REMOVEAPOSTROPHECOMMENT			L"Kommentare entfernen [ ; ]"
#define				_UI_PROPWND_REMOVEBRACKETCOMMENT			L"Klammer-Kommentare entfernen [ (...)  {...} ]"
#define				_UI_PROPWND_REMOVESPACES					L"Leerzeichen entfernen"



#define				_UI_EXPLORER_TOOLTIP_LOADROOTFOLDER			L"Stammverzeichnis wählen"
#define				_UI_EXPLORER_TOOLTIP_NEWPROGRAMM			L"Neues NC-Programm zu ausgewähltem Ordner hinzufügen"
#define				_UI_EXPLORER_TOOLTIP_NEWFOLDER				L"Neuen Unterordner in ausgewähltem Verzeichnis erstellen"
#define				_UI_EXPLORER_TOOLTIP_COPYELEMENT			L"Element kopieren"
#define				_UI_EXPLORER_TOOLTIP_INSERTELEMENT			L"Element einfügen"
#define				_UI_EXPLORER_TOOLTIP_DELETEELEMENT			L"Element löschen"
#define				_UI_EXPLORER_TOOLTIP_CONVERTTOCNC3			L"Element in cnc3 Datei umwandeln"
#define				_UI_EXPLORER_TOOLTIP_IMPORTCONTENT			L"Inhalt importieren"
#define				_UI_EXPLORER_TOOLTIP_SEARCHFORPROGRAMM		L"Nach NC-Programmen suchen"


#define				_UI_SSCREEN_LOADING					L"Wird geladen..."
#define				_UI_SSCREEN_INITAPPDATA				L"Anwendungsdaten werden initialisiert"
#define				_UI_SSCREEN_VERIFYFILESYSTEM		L"Dateisystem wird verifiziert"
#define				_UI_SSCREEN_LOADEDITRESOURCES		L"Initialisiere Editor-Resourcen"
#define				_UI_SSCREEN_INITMAINFRAME			L"Anwendungsoberfläche wird geladen"


#define				_UI_STATUSBAR_READY_STATE			L"Bereit"
#define				_UI_STATUSBAR_SENDINPROGRESS		L"Daten werden gesendet..."
#define				_UI_STATUSBAR_RECEIVEINPROGRESS		L"Empfange Daten..."

#define				_UI_PROGRESS_COLLECTINGDATA			L"Daten werden gesammelt ..."
#define				_UI_PROGRESS_LOADINGDATA			L"Daten werden geladen ..."

#define				_UI_SEARCHCTRL_MAXSRCHRESULT		L"Mehr als 300 Ergebnisse..."

#define				_UI_RESETWND_CHOOSECOMPONENT		L"Komponente wählen:"
#define				_UI_RESETWND_COMPARAMETER			L"COM Schnittstellenparameter"
#define				_UI_RESETWND_COMMONSETTINGS			L"CnC Suite Einstellungen"
#define				_UI_RESETWND_AUTOSYNTAXSETUP		L"Autosyntax Einstellungen"
#define				_UI_RESETWND_USERTEXT				L"Benutzerdefinierter Text"
#define				_UI_RESETWND_INTERNALSETUP			L"Interne Einstellungen"
#define				_UI_RESETWND_AUTOCOMPLETESETUP		L"Autocomplete Daten"
#define				_UI_RESETWND_APPDATA				L"Anwendungsdaten"
#define				_UI_RESETWND_SESSIONDATA			L"Sitzungsdaten"
#define				_UI_RESETWND_RESTARTMESSAGE			L"Die Anwendung muss neu gestartet werden."

#define				_UI_PROPWND_SAVEHISTORY				L"Chronik anlegen"
#define				_UI_PROPWND_DELETEHISTORYNOW		L"Chronik löschen"


#define				_UI_GNRL_COPYRIGHT					L"\xa9 2018 LaroomySoft"
#define				_UI_GNRL_RIGHTS						L"Alle Rechte vorbehalten."
#define				_UI_GNRL_USERCANCELCONFIRM			L"Wird abgebrochen..."
#define				_UI_GNRL_NEWSUBFOLDER				L"Neuer Unterordner"
#define				_UI_GNRL_LINEENDFORMAT				L"Zeilenende:"
#define				_UI_GNRL_HISTORY					L"Chronik"
#define				_UI_GNRL_STARTUPTEXTPLACEHOLDER		L"  %5555\n\nN   1 "
#define				_UI_GNRL_SEARCHINFOLDER				L"Durchsuchen..."


#define				_UI_FILETIME_CREATED				L"Erstellt:        "
#define				_UI_FILETIME_LASTWRITE				L"Zuletzt geändert:"
#define				_UI_FILETIME_LASTACCESS				L"Letzter Zugriff: "
#define				_UI_FILEINFO						L"Datei"
#define				_UI_FILESIZE						L"Dateigröße:      "
#define				_UI_OUTPUTSIZE						L"Ausgabegröße:    "
#define				_UI_PATH							L"Pfad"




// ERROR MESSAGES >>
#define				_UI_XML_ERR_UNEXPECTEDCLOSINGTAG	L"XML-Syntaxfehler: unerwartetes TAG-Ende.  Index: \0"
#define				_UI_XML_ERR_DOCUMENTFORMAT_INVALID	L"XML-Fehler: Dokumentformat ungültig.\0"
#define				_UI_XML_ERR_NOCLOSING_ELEMENT_P1	L"XML-Syntaxfehler: Schließendes Element für \"\0"
#define				_UI_XML_ERR_NOCLOSING_ELEMENT_P2	L"\" wurde nicht gefunden. Index: \0"

#define				_ERROR_MSG_FILETYPE_NOTSUPPORTED	L"Dieses Dateiformat wird nicht unterstützt. Benutzen Sie die Import-Funktion um fremde Daten anzuzeigen.\0"
#define				_ERROR_MSG_ROOTFOLDERINVALIDATED	L"Der aktuelle Stammordner ist ungültig geworden. Bitte wählen Sie einen neuen Ordner."
#define				_ERROR_MSG_ROOTFOLDERLOADINGFAILED	L"(E_UNEXPECTED) Laden des Stammordners fehlgeschlagen."
#define				_ERROR_MSG_DRIVELOADINGNOTALLOWED	L"Ein komplettes Laufwerk kann nicht geladen werden. Bitte wählen Sie einen Unterordner."
#define				_ERROR_MSG_EXPORT_FAILED			L"Export fehlgeschlagen. Fehlercode: "
#define				_ERROR_MSG_OPENFILE_FAILED			L"Öffnen der Datei fehlgeschlagen. Fehlercode: "
#define				_ERROR_MSG_IMPORT_FAILED			L"Importieren der Datei fehlgeschlagen. Fehlercode "
#define				_ERROR_MSG_CNC3FILEOBJECT_ERROR		L"CnC3FileObject error. Errorcode "
#define				_ERROR_MSG_OPENFOLDER_FAILED		L"Ordner konnte nicht geöffnet werden. Fehlercode "




// WARNINGS >>
#define				_WARNING_MSG_UPDATESEARCH_FAILED	L"Suche nach Updates fehlgeschlagen - Keine Internetverbindung\0"
#define				_WARNING_MSG_SAVEALL_NOPATHFOUND	L"Für einen oder mehr Tabs ist kein gültiges Zielverzeichnis vorhanden."



// INFORMATION >>
#define				_INFO_MSG_FILEWASIMPORTED			L"Autoimport erfolgreich ausgeführt für Datei: \0"
#define				_INFO_MSG_FILEWASCONVERTED			L"Dateikonvertierung erfolgreich für Datei: \0"
#define				_INFO_MSG_UPDATEAVAILABLE			L"Ein Update ist verfügbar.\0"
#define				_INFO_MSG_LASTTABNOCLOSE			L"Letzter Tab kann nicht geschlossen werden.\0"
#define				_INFO_MSG_MAXIMUMTABCOUNTREACHED	L"Die maximale Tab-Anzahl ist erreicht.\0"
#define				_INFO_MSG_FILEISALREADYOPEN			L"Datei ist bereits geöffnet."
#define				_INFO_MSG_CHANGESNEEDRESTART		L"Die angeforderten Änderungen erfordern einen Programmneustart."
#define				_INFO_MSG_NOTARGETSELECTED			L"Kein Ziel ausgewählt"
#define				_INFO_MSG_NOHISTORYCONTENT			L"Keine Chronik-Einträge gefunden."



// DIALOG STRINGS >>
#define				_DLG_MSG_FILENOTSAVEDSAVENOW		L" ist nicht gespeichert. Jetzt speichern?\0"
#define				_DLG_MSG_UNSAVEDCONTENTEXISTS		L" Tabs enthalten ungespeicherten Inhalt. Trotzdem schließen?\0"